# Generated by Django 5.0.2 on 2024-02-15 09:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = []
