# Generated by Django 5.0.2 on 2024-02-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_auto_20240215_1405"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
